apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor-service
  template:
    metadata:
      labels:
        app: processor-service
    spec:
      containers:
        - name: processor-service
          image: uptime-monitor-processor_service:v1.5.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          env:
            - name: KAFKA_BROKER
              value: "kafka:9092"
            - name: REDIS_HOST
              value: "redis"
            - name: USER_SERVICE_URL
              value: "http://user_service:5000"
            - name: INTERNAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: uptime-secrets
                  key: INTERNAL_API_KEY
