apiVersion: v1
kind: Secret
metadata:
  name: uptime-secrets
type: Opaque
data:
  # Base64 encoded values for production hardening
  SECRET_KEY: dXB0aW1lLW1vbml0b3Itc3VwZXItc2VjcmV0LWtleQ==
  INTERNAL_API_KEY: aW50ZXJuYWwtc2VydmljZS1zaGFyZWQtc2VjcmV0LWtleQ==
  POSTGRES_PASSWORD: dXB0aW1lX3Bhc3N3b3Jk
